# docker-Specify the compose version
version: "3"

services:
  app:
    # build: .
    image: pudding/github-action-app:puppeteer-python-14-20230802-2136
    tty: true
    volumes: 
      - ./startup.sh:/startup.sh
      - ./app:/app/
      - ./output:/output/
      - ./cache:/cache/
      - ./config.js:/config.js